package com.ecommerce.paymentservice.application.dto.request;

import com.ecommerce.paymentservice.infrastructure.persistence.entity.PaymentMethod;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;

/**
 * Inbound request DTO for initiating a new payment.
 *
 * <p>Received by the REST controller as the request body for
 * {@code POST /api/v1/payments}. All fields are validated with
 * Jakarta Bean Validation before being passed to the service layer.
 *
 * <p>Fields intentionally excluded from this request:
 * <ul>
 *   <li>{@code paymentId}    — generated by the database</li>
 *   <li>{@code paymentStatus}— always set to {@code PENDING} on creation</li>
 *   <li>{@code transactionId}— assigned by the payment gateway after processing</li>
 *   <li>{@code paymentDate}  — set to the current timestamp by the service</li>
 * </ul>
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PaymentRequest {

    /**
     * The ID of the order this payment is for.
     *
     * <p>Used as an idempotency key — the service will reject a
     * duplicate payment request for the same order ID.
     *
     * <p>Must not be {@code null}.
     */
    @NotNull(message = "Order ID is required")
    private Long orderId;

    /**
     * The ID of the customer initiating the payment.
     *
     * <p>Must not be {@code null}.
     */
    @NotNull(message = "Customer ID is required")
    private Long customerId;

    /**
     * The payment amount.
     *
     * <p>Must not be {@code null} and must be strictly greater than zero.
     * Negative amounts and zero-value payments are rejected.
     */
    @NotNull(message = "Amount is required")
    @Positive(message = "Amount must be greater than zero")
    private BigDecimal amount;

    /**
     * The payment instrument chosen by the customer.
     *
     * <p>Must not be {@code null} and must match one of the supported
     * {@link PaymentMethod} values:
     * {@code CREDIT_CARD}, {@code DEBIT_CARD}, {@code ONLINE_BANKING}, {@code E_WALLET}.
     */
    @NotNull(message = "Payment method is required")
    private PaymentMethod paymentMethod;

}
